import { EngineeringUnits } from "./enum";

export function getEngineeringUnitHumanReadable(
  engineeringUnit: EngineeringUnits,
  desiredOutput: "readable" | "scientific" = "scientific"
): string {
  return friendlyEngineeringUnits[engineeringUnit][
    desiredOutput === "readable" ? 0 : 1
  ];
}

type ReadbaleUnit = string;
type ScientificUnit = string;
type FriendlyEngineeringUnits = Record<
  EngineeringUnits & "285" & "SQUARE_METERS(0)",
  [ReadbaleUnit, ScientificUnit]
>;

const friendlyEngineeringUnits: FriendlyEngineeringUnits = {
  // ERROR -> No Unit should be displayed
  "285": [" ", " "],

  // a bug that results booleans to be displayed as engineering units
  "SQUARE_METERS(0)": ["True/False", " "],
  METERS_PER_SECOND_PER_SECOND: ["Acceleration", "m/s²"],
  SQUARE_METERS: ["Area", "m²"],
  SQUARE_CENTIMETERS: ["Area", "cm²"],
  SQUARE_FEET: ["Area", "ft²"],
  SQUARE_INCHES: ["Area", "in²"],
  CURRENCY1: ["Currency", "Currency1"],
  CURRENCY2: ["Currency", "Currency2"],
  CURRENCY3: ["Currency", "Currency3"],
  CURRENCY4: ["Currency", "Currency4"],
  CURRENCY5: ["Currency", "Currency5"],
  CURRENCY6: ["Currency", "Currency6"],
  CURRENCY7: ["Currency", "Currency7"],
  CURRENCY8: ["Currency", "Currency8"],
  CURRENCY9: ["Currency", "Currency9"],
  CURRENCY10: ["Currency", "Currency10"],
  MILLIAMPERES: ["Electric Current", "mA"],
  AMPERES: ["Electric Current", "A"],
  AMPERES_PER_METER: ["Electric Current Density", "A/m"],
  AMPERES_PER_SQUARE_METER: ["Current Density", "A/m²"],
  AMPERE_SQUARE_METERS: ["Electric Current", "As/m²"],
  DECIBELS: ["Decibels", "dB"],
  DECIBELS_MILLIVOLT: ["Decibels (mV)", "dBmV"],
  DECIBELS_VOLT: ["Decibels (V)", "dBV"],
  FARADS: ["Capacitance", "F"],
  HENRYS: ["Inductance", "H"],
  OHMS: ["Resistance", "Ω"],
  OHM_METER_SQUARED_PER_METER: ["Resistivity", "Ω·m²/m"],
  OHM_METERS: ["Resistance", "Ω·m"],
  MILLIOHMS: ["Resistance", "mΩ"],
  KILOHMS: ["Resistance", "kΩ"],
  MEGOHMS: ["Resistance", "MΩ"],
  MICROSIEMENS: ["Conductance", "µS"],
  MILLISIEMENS: ["Conductance", "mS"],
  SIEMENS: ["Conductance", "S"],
  SIEMENS_PER_METER: ["Conductivity", "S/m"],
  TESLAS: ["Magnetic Flux Density", "T"],
  VOLTS: ["Voltage", "V"],
  MILLIVOLTS: ["Voltage", "mV"],
  KILOVOLTS: ["Voltage", "kV"],
  MEGAVOLTS: ["Voltage", "MV"],
  VOLT_AMPERES: ["Apparent Power", "VA"],
  KILOVOLT_AMPERES: ["Apparent Power", "kVA"],
  MEGAVOLT_AMPERES: ["Apparent Power", "MVA"],
  VOLT_AMPERES_REACTIVE: ["Reactive Power", "VAR"],
  KILOVOLT_AMPERES_REACTIVE: ["Reactive Power", "kVAR"],
  MEGAVOLT_AMPERES_REACTIVE: ["Reactive Power", "MVAR"],
  VOLTS_PER_DEGREE_KELVIN: ["Voltage per Degree Kelvin", "V/°K"],
  VOLTS_PER_METER: ["Electric Field Strength", "V/m"],
  DEGREES_PHASE: ["Angle", "°"],
  POWER_FACTOR: ["Power Factor", ""],
  WEBERS: ["Magnetic Flux", "Wb"],

  AMPERE_SECONDS: ["Electric Charge", "As"],
  VOLT_AMPERE_HOURS: ["Apparent Energy", "VAh"],
  KILOVOLT_AMPERE_HOURS: ["Apparent Energy", "kVAh"],
  MEGAVOLT_AMPERE_HOURS: ["Apparent Energy", "MVAh"],
  VOLT_AMPERE_HOURS_REACTIVE: ["Reactive Energy", "VARh"],
  KILOVOLT_AMPERE_HOURS_REACTIVE: ["Reactive Energy", "kVARh"],
  MEGAVOLT_AMPERE_HOURS_REACTIVE: ["Reactive Energy", "MVARh"],
  VOLT_SQUARE_HOURS: ["Volt Square Hours", "V²h"],
  AMPERE_SQUARE_HOURS: ["Ampere Square Hours", "A²h"],
  JOULES: ["Energy", "J"],
  KILOJOULES: ["Energy", "kJ"],
  KILOJOULES_PER_KILOGRAM: ["Specific Energy", "kJ/kg"],
  MEGAJOULES: ["Energy", "MJ"],
  WATT_HOURS: ["Energy", "Wh"],
  KILOWATT_HOURS: ["Energy", "kWh"],
  MEGAWATT_HOURS: ["Energy", "MWh"],
  WATT_HOURS_REACTIVE: ["Reactive Energy", "VARh"],
  KILOWATT_HOURS_REACTIVE: ["Reactive Energy", "kVARh"],
  MEGAWATT_HOURS_REACTIVE: ["Reactive Energy", "MVARh"],
  BTUS: ["Energy", "BTU"],
  KILO_BTUS: ["Energy", "kBTU"],
  MEGA_BTUS: ["Energy", "MBTU"],
  THERMS: ["Energy", "Therm"],
  TON_HOURS: ["Energy", "Ton-hour"],
  JOULES_PER_KILOGRAM_DRY_AIR: ["Specific Energy", "J/kg"],
  KILOJOULES_PER_KILOGRAM_DRY_AIR: ["Specific Energy", "kJ/kg"],
  MEGAJOULES_PER_KILOGRAM_DRY_AIR: ["Specific Energy", "MJ/kg"],
  BTUS_PER_POUND_DRY_AIR: ["Specific Energy", "BTU/lb"],
  BTUS_PER_POUND: ["Energy", "BTU/lb"],
  JOULES_PER_DEGREE_KELVIN: ["Specific Heat Capacity", "J/(K)"],
  KILOJOULES_PER_DEGREE_KELVIN: ["Specific Heat Capacity", "kJ/(K)"],
  MEGAJOULES_PER_DEGREE_KELVIN: ["Specific Heat Capacity", "MJ/(K)"],
  JOULES_PER_KILOGRAM_DEGREE_KELVIN: ["Specific Heat Capacity", "J/(kg·K)"],
  NEWTON: ["Force", "N"],
  CYCLES_PER_HOUR: ["Frequency", "cph"],
  CYCLES_PER_MINUTE: ["Frequency", "cpm"],
  HERTZ: ["Frequency", "Hz"],
  KILOHERTZ: ["Frequency", "kHz"],
  MEGAHERTZ: ["Frequency", "MHz"],
  PER_HOUR: ["Rate", "1/h"],
  GRAMS_OF_WATER_PER_KILOGRAM_DRY_AIR: ["Specific Humidity", "g/kg"],
  PERCENT_RELATIVE_HUMIDITY: ["Relative Humidity", "%"],
  MICROMETERS: ["Length", "µm"],
  MILLIMETERS: ["Length", "mm"],
  CENTIMETERS: ["Length", "cm"],
  KILOMETERS: ["Length", "km"],
  METERS: ["Length", "m"],
  INCHES: ["Length", "in"],
  FEET: ["Length", "ft"],

  CANDELAS: ["Luminous Intensity", "cd"],
  CANDELAS_PER_SQUARE_METER: ["Luminance", "cd/m²"],
  WATTS_PER_SQUARE_FOOT: ["Illuminance", "W/ft²"],
  WATTS_PER_SQUARE_METER: ["Illuminance", "W/m²"],
  LUMENS: ["Luminous Flux", "lm"],
  LUXES: ["Illuminance", "lux"],
  FOOT_CANDLES: ["Illuminance", "fc"],
  MILLIGRAMS: ["Mass", "mg"],
  GRAMS: ["Mass", "g"],
  KILOGRAMS: ["Mass", "kg"],
  POUNDS_MASS: ["Mass", "lb"],
  TONS: ["Mass", "ton"],
  GRAMS_PER_SECOND: ["Mass Flow Rate", "g/s"],
  GRAMS_PER_MINUTE: ["Mass Flow Rate", "g/min"],
  KILOGRAMS_PER_SECOND: ["Mass Flow Rate", "kg/s"],
  KILOGRAMS_PER_MINUTE: ["Mass Flow Rate", "kg/min"],
  KILOGRAMS_PER_HOUR: ["Mass Flow Rate", "kg/h"],
  POUNDS_MASS_PER_SECOND: ["Mass Flow Rate", "lb/s"],
  POUNDS_MASS_PER_MINUTE: ["Mass Flow Rate", "lb/min"],
  POUNDS_MASS_PER_HOUR: ["Mass Flow Rate", "lb/h"],
  TONS_PER_HOUR: ["Mass Flow Rate", "ton/h"],
  MILLIWATTS: ["Power", "mW"],
  WATTS: ["Power", "W"],
  KILOWATTS: ["Power", "kW"],
  MEGAWATTS: ["Power", "MW"],
  BTUS_PER_HOUR: ["Power", "BTU/h"],
  KILO_BTUS_PER_HOUR: ["Power", "kBTU/h"],
  JOULE_PER_HOURS: ["Energy", "J/h"],
  HORSEPOWER: ["Power", "hp"],
  TONS_REFRIGERATION: ["Power", "ton"],
  PASCALS: ["Pressure", "Pa"],
  HECTOPASCALS: ["Pressure", "hPa"],
  KILOPASCALS: ["Pressure", "kPa"],
  MILLIBARS: ["Pressure", "mbar"],
  BARS: ["Pressure", "bar"],
  POUNDS_FORCE_PER_SQUARE_INCH: ["Pressure", "psi"],
  MILLIMETERS_OF_WATER: ["Pressure", "mmH2O"],
  CENTIMETERS_OF_WATER: ["Pressure", "cmH2O"],
  INCHES_OF_WATER: ["Pressure", "inH2O"],
  MILLIMETERS_OF_MERCURY: ["Pressure", "mmHg"],
  CENTIMETERS_OF_MERCURY: ["Pressure", "cmHg"],
  INCHES_OF_MERCURY: ["Pressure", "inHg"],
  DEGREES_CELSIUS: ["Temperature", "°C"],
  DEGREES_KELVIN: ["Temperature", "K"],
  DEGREES_KELVIN_PER_HOUR: ["Temperature Rate", "K/h"],
  DEGREES_KELVIN_PER_MINUTE: ["Temperature Rate", "K/min"],
  DEGREES_FAHRENHEIT: ["Temperature", "°F"],
  DEGREE_DAYS_CELSIUS: ["Temperature", "°C-days"],
  DEGREE_DAYS_FAHRENHEIT: ["Temperature", "°F-days"],
  DELTA_DEGREES_FAHRENHEIT: ["Temperature Difference", "Δ°F"],
  DELTA_DEGREES_KELVIN: ["Temperature Difference", "ΔK"],

  YEARS: ["Time", "years"],
  MONTHS: ["Time", "months"],
  WEEKS: ["Time", "weeks"],
  DAYS: ["Time", "days"],
  HOURS: ["Time", "hours"],
  MINUTES: ["Time", "minutes"],
  SECONDS: ["Time", "seconds"],
  HUNDREDTHS_SECONDS: ["Time", "hundredths of a second"],
  MILLISECONDS: ["Time", "milliseconds"],
  NEWTON_METERS: ["Torque", "N·m"],
  MILLIMETERS_PER_SECOND: ["Speed", "mm/s"],
  MILLIMETERS_PER_MINUTE: ["Speed", "mm/min"],
  METERS_PER_SECOND: ["Speed", "m/s"],
  METERS_PER_MINUTE: ["Speed", "m/min"],
  METERS_PER_HOUR: ["Speed", "m/h"],
  KILOMETERS_PER_HOUR: ["Speed", "km/h"],
  FEET_PER_SECOND: ["Speed", "ft/s"],
  FEET_PER_MINUTE: ["Speed", "ft/min"],
  MILES_PER_HOUR: ["Speed", "mi/h"],
  CUBIC_FEET: ["Volume", "ft³"],
  CUBIC_METERS: ["Volume", "m³"],
  IMPERIAL_GALLONS: ["Volume", "Imperial gallons"],
  MILLILITERS: ["Volume", "mL"],
  LITERS: ["Volume", "L"],
  US_GALLONS: ["Volume", "US gallons"],
  CUBIC_FEET_PER_SECOND: ["Flow Rate", "ft³/s"],
  CUBIC_FEET_PER_MINUTE: ["Flow Rate", "ft³/min"],
  MILLION_STANDARD_CUBIC_FEET_PER_MINUTE: ["Flow Rate", "MMSCFD"],
  CUBIC_FEET_PER_HOUR: ["Flow Rate", "ft³/h"],
  CUBIC_FEET_PER_DAY: ["Flow Rate", "ft³/d"],
  STANDARD_CUBIC_FEET_PER_DAY: ["Flow Rate", "SCFD"],
  MILLION_STANDARD_CUBIC_FEET_PER_DAY: ["Flow Rate", "MMSCFD"],
  THOUSAND_CUBIC_FEET_PER_DAY: ["Flow Rate", "MCFD"],
  THOUSAND_STANDARD_CUBIC_FEET_PER_DAY: ["Flow Rate", "MSCFD"],
  POUNDS_MASS_PER_DAY: ["Mass Flow Rate", "lb/d"],
  CUBIC_METERS_PER_SECOND: ["Flow Rate", "m³/s"],
  CUBIC_METERS_PER_MINUTE: ["Flow Rate", "m³/min"],
  CUBIC_METERS_PER_HOUR: ["Flow Rate", "m³/h"],
  CUBIC_METERS_PER_DAY: ["Flow Rate", "m³/d"],
  IMPERIAL_GALLONS_PER_MINUTE: ["Flow Rate", "Imperial GPM"],
  MILLILITERS_PER_SECOND: ["Flow Rate", "mL/s"],
  LITERS_PER_SECOND: ["Flow Rate", "L/s"],
  LITERS_PER_MINUTE: ["Flow Rate", "L/min"],
  LITERS_PER_HOUR: ["Flow Rate", "L/h"],
  US_GALLONS_PER_MINUTE: ["Flow Rate", "US GPM"],
  US_GALLONS_PER_HOUR: ["Flow Rate", "US GPH"],
  DEGREES_ANGULAR: ["Angular Measure", "°"],
  DEGREES_CELSIUS_PER_HOUR: ["Temperature Rate", "°C/h"],
  DEGREES_CELSIUS_PER_MINUTE: ["Temperature Rate", "°C/min"],
  DEGREES_FAHRENHEIT_PER_HOUR: ["Temperature Rate", "°F/h"],
  DEGREES_FAHRENHEIT_PER_MINUTE: ["Temperature Rate", "°F/min"],
  JOULE_SECONDS: ["Energy", "J·s"],

  KILOGRAMS_PER_CUBIC_METER: ["Density", "kg/m³"],
  KILOWATT_HOURS_PER_SQUARE_METER: ["Energy/Area", "kWh/m²"],
  KILOWATT_HOURS_PER_SQUARE_FOOT: ["Energy/Area", "kWh/ft²"],
  WATT_HOURS_PER_CUBIC_METER: ["Energy/Volume", "Wh/m³"],
  JOULES_PER_CUBIC_METER: ["Energy/Volume", "J/m³"],
  MEGAJOULES_PER_SQUARE_METER: ["Energy/Area", "MJ/m²"],
  MEGAJOULES_PER_SQUARE_FOOT: ["Energy/Area", "MJ/ft²"],
  MOLE_PERCENT: ["Mole Percentage", "mol%"],
  NO_UNITS: ["No Units", ""],
  NEWTON_SECONDS: ["Torque", "N·s"],
  NEWTONS_PER_METER: ["Force/Length", "N/m"],
  PARTS_PER_MILLION: ["Parts Per Million", "ppm"],
  PARTS_PER_BILLION: ["Parts Per Billion", "ppb"],
  PASCAL_SECONDS: ["Dynamic Viscosity", "Pa·s"],
  PERCENT: ["Percentage", "%"],
  PERCENT_OBSCURATION_PER_FOOT: ["Obscuration Percentage/Foot", "%/ft"],
  PERCENT_OBSCURATION_PER_METER: ["Obscuration Percentage/Meter", "%/m"],
  PERCENT_PER_SECOND: ["Percentage/Time", "%/s"],
  PER_MINUTE: ["Rate", "/min"],
  PER_SECOND: ["Rate", "/s"],
  PSI_PER_DEGREE_FAHRENHEIT: ["Pressure Change", "psi/°F"],
  RADIANS: ["Angular Measure", "rad"],
  RADIANS_PER_SECOND: ["Angular Velocity", "rad/s"],
  REVOLUTIONS_PER_MINUTE: ["Rotational Speed", "rpm"],
  SQUARE_METERS_PER_NEWTON: ["Area/Force", "m²/N"],
  WATTS_PER_METER_PER_DEGREE_KELVIN: ["Thermal Conductance", "W/(m·K)"],
  WATTS_PER_SQUARE_METER_DEGREE_KELVIN: ["Thermal Conductivity", "W/(m²·K)"],
  PER_MILLE: ["Per Mille", "‰"],
  GRAMS_PER_GRAM: ["Specific Mass", "g/g"],
  KILOGRAMS_PER_KILOGRAM: ["Specific Mass", "kg/kg"],
  GRAMS_PER_KILOGRAM: ["Mass Ratio", "g/kg"],
  MILLIGRAMS_PER_GRAM: ["Specific Mass", "mg/g"],
  MILLIGRAMS_PER_KILOGRAM: ["Mass Ratio", "mg/kg"],
  GRAMS_PER_MILLILITER: ["Density", "g/mL"],
  GRAMS_PER_LITER: ["Density", "g/L"],
  MILLIGRAMS_PER_LITER: ["Density", "mg/L"],
  MICROGRAMS_PER_LITER: ["Density", "µg/L"],
  GRAMS_PER_CUBIC_METER: ["Density", "g/m³"],
  MILLIGRAMS_PER_CUBIC_METER: ["Density", "mg/m³"],
  MICROGRAMS_PER_CUBIC_METER: ["Density", "µg/m³"],
  NANOGRAMS_PER_CUBIC_METER: ["Density", "ng/m³"],
  GRAMS_PER_CUBIC_CENTIMETER: ["Density", "g/cm³"],
  BECQUERELS: ["Radioactivity", "Bq"],
  KILOBECQUERELS: ["Radioactivity", "kBq"],
  MEGABECQUERELS: ["Radioactivity", "MBq"],
  GRAY: ["Absorbed Dose", "Gy"],
  MILLIGRAY: ["Absorbed Dose", "mGy"],
  MICROGRAY: ["Absorbed Dose", "µGy"],
  SIEVERTS: ["Dose Equivalent", "Sv"],
  MILLISIEVERTS: ["Dose Equivalent", "mSv"],
  MICROSIEVERTS: ["Dose Equivalent", "µSv"],
  MICROSIEVERTS_PER_HOUR: ["Dose Rate", "µSv/h"],
  MILLIREMS: ["Dose Equivalent", "mrem"],
  MILLIREMS_PER_HOUR: ["Dose Rate", "mrem/h"],
  DECIBELS_A: ["Sound Level", "dB(A)"],
  NEPHELOMETRIC_TURBIDITY_UNIT: ["Turbidity", "NTU"],
  PH: ["Acidity/Alkalinity", "pH"],
  GRAMS_PER_SQUARE_METER: ["Mass/Area", "g/m²"],
  MINUTES_PER_DEGREE_KELVIN: ["Time/Thermal Inertia", "min/(°K)"],
};
